# Generated by Django 3.1.7 on 2021-03-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='blogpost',
        ),
    ]
